#:schema node_modules/wrangler/config-schema.json
name = "sublink-worker-liangchenzhou1"
main = "src/worker.jsx"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "bbf6f2ae10a045538e91d1505faf44e3" }
]

[assets]
directory = "./public"
